import { useState } from 'react';
import { Copy, Check, Download, FileCode } from 'lucide-react';
import type { WorkflowConfig } from '../types';

interface Props {
  config: WorkflowConfig;
}

export function YamlPreview({ config }: Props) {
  const [copied, setCopied] = useState(false);
  const yaml = generateYaml(config);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(yaml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.name.toLowerCase().replace(/\s+/g, '-')}.yml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="card">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-lg font-semibold text-white flex items-center gap-2">
          <FileCode className="w-5 h-5 text-claude-500" />
          Generated GitHub Actions Workflow
        </h2>
        <div className="flex items-center gap-2">
          <button onClick={handleCopy} className="btn-secondary flex items-center gap-2">
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>
          <button onClick={handleDownload} className="btn-primary flex items-center gap-2">
            <Download className="w-4 h-4" />
            <span>Download .yml</span>
          </button>
        </div>
      </div>

      <div className="relative">
        <pre className="code-block overflow-x-auto max-h-[600px] overflow-y-auto">
          <code dangerouslySetInnerHTML={{ __html: highlightYaml(yaml) }} />
        </pre>
      </div>

      <div className="mt-6 p-4 bg-dark-800/50 rounded-lg border border-dark-700">
        <h3 className="text-sm font-medium text-dark-300 mb-2">Quick Start</h3>
        <ol className="text-sm text-dark-400 space-y-1 list-decimal list-inside">
          <li>Download the workflow file or copy the YAML above</li>
          <li>
            Create <code className="text-claude-400">.github/workflows/</code> directory in your repo
          </li>
          <li>Save the file as <code className="text-claude-400">{config.name.toLowerCase().replace(/\s+/g, '-')}.yml</code></li>
          <li>
            Set <code className="text-claude-400">ANTHROPIC_API_KEY</code> in your repository secrets
          </li>
          <li>Push to trigger the workflow</li>
        </ol>
      </div>
    </div>
  );
}

function generateYaml(config: WorkflowConfig): string {
  const triggers: string[] = [];

  if (config.triggers.pullRequest) {
    triggers.push(`  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
${config.branches.map((b) => `      - ${b}`).join('\n')}`);
  }

  if (config.triggers.push) {
    triggers.push(`  push:
    branches:
${config.branches.map((b) => `      - ${b}`).join('\n')}`);
  }

  if (config.triggers.manual) {
    triggers.push(`  workflow_dispatch:
    inputs:
      review_scope:
        description: 'Review scope'
        required: false
        default: '${config.reviewScope}'
        type: choice
        options:
          - full
          - diff
          - security`);
  }

  const modelMap = {
    opus: 'claude-opus-4-5-20250514',
    sonnet: 'claude-sonnet-4-20250514',
    haiku: 'claude-haiku-3-5-20241022',
  };

  const thinkingBudget = {
    ultrathink: '128000',
    extended: '32000',
    normal: '8000',
  };

  return `# ${config.name}
# Generated by Claude Workflow Builder
# https://github.com/anthropics/claude-code

name: ${config.name}

on:
${triggers.join('\n')}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-review:
    name: Claude Code Review
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Claude Code
        run: npm install -g @anthropic-ai/claude-code

      - name: Run Claude Code Review
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_MODEL: ${modelMap[config.model]}
          THINKING_BUDGET: ${thinkingBudget[config.thinkingMode]}
        run: |
          claude-code review \\
            --model "\$CLAUDE_MODEL" \\
            --thinking-budget "\$THINKING_BUDGET" \\
            --scope "${config.reviewScope}" \\
            ${config.createComments ? '--create-comments' : '--no-comments'} \\
            ${config.autoFix ? '--auto-fix' : ''} \\
            --output review-results.json

      - name: Upload Review Results
        uses: actions/upload-artifact@v4
        with:
          name: claude-review-results
          path: review-results.json
          retention-days: 30

      ${
        config.blockOnIssues
          ? `- name: Check for Critical Issues
        run: |
          if grep -q '"severity": "error"' review-results.json; then
            echo "Critical issues found. Blocking merge."
            exit 1
          fi`
          : ''
      }

      - name: Post Review Summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('review-results.json', 'utf8'));

            const summary = \`## Claude Code Review Summary

            **Model**: ${modelMap[config.model]}
            **Thinking Mode**: ${config.thinkingMode}
            **Scope**: ${config.reviewScope}

            ---

            \${results.summary || 'Review completed successfully.'}
            \`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
`;
}

function highlightYaml(yaml: string): string {
  return yaml
    .replace(/(#[^\n]*)/g, '<span class="yaml-comment">$1</span>')
    .replace(/^(\s*)([a-zA-Z_-]+)(:)/gm, '$1<span class="yaml-key">$2</span>$3')
    .replace(/: '([^']*)'/g, ": '<span class=\"yaml-string\">$1</span>'")
    .replace(/: "([^"]*)"/g, ': "<span class="yaml-string">$1</span>"')
    .replace(/: (true|false)/g, ': <span class="yaml-boolean">$1</span>')
    .replace(/: (\d+)/g, ': <span class="yaml-number">$1</span>')
    .replace(/\$\{\{([^}]+)\}\}/g, '<span class="text-amber-400">\${{$1}}</span>');
}
