/**
 * OpenAPI specification generator for the Workflow Architect API
 * Generates complete OpenAPI 3.0 spec with all endpoints
 */

export interface OpenAPISpec {
	openapi: string;
	info: { title: string; version: string; description: string };
	servers: Array<{ url: string; description: string }>;
	paths: Record<string, unknown>;
	components: { schemas: Record<string, unknown>; securitySchemes: Record<string, unknown> };
}

/**
 * Generate OpenAPI specification
 * Integration: const spec = new OpenAPIGenerator().generateSpec();
 */
export class OpenAPIGenerator {
	generateSpec(): OpenAPISpec {
		return {
			openapi: '3.0.0',
			info: {
				title: 'Workflow Architect API',
				version: '1.0.0',
				description: 'REST API for managing workflows, executions, and templates',
			},
			servers: [
				{ url: 'http://localhost:3000', description: 'Development server' },
				{ url: 'https://api.workflow-architect.com', description: 'Production server' },
			],
			paths: {
				'/workflows': {
					get: {
						summary: 'List workflows',
						parameters: [
							{ name: 'limit', in: 'query', schema: { type: 'integer', default: 20 } },
							{ name: 'cursor', in: 'query', schema: { type: 'string' } },
						],
						responses: {
							'200': { description: 'Success', content: { 'application/json': { schema: { $ref: '#/components/schemas/WorkflowList' } } } },
						},
					},
					post: {
						summary: 'Create workflow',
						requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Workflow' } } } },
						responses: {
							'201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/Workflow' } } } },
						},
					},
				},
			},
			components: {
				schemas: {
					Workflow: {
						type: 'object',
						properties: {
							id: { type: 'string', format: 'uuid' },
							name: { type: 'string' },
							description: { type: 'string' },
							nodes: { type: 'array', items: { type: 'object' } },
						},
					},
					WorkflowList: {
						type: 'object',
						properties: {
							items: { type: 'array', items: { $ref: '#/components/schemas/Workflow' } },
							cursor: { type: 'string' },
							hasMore: { type: 'boolean' },
						},
					},
				},
				securitySchemes: {
					bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
				},
			},
		};
	}

	toJSON(): string {
		return JSON.stringify(this.generateSpec(), null, 2);
	}

	toYAML(): string {
		// Simplified YAML generation - in production use a proper YAML library
		return '# OpenAPI 3.0.0 Specification\n# Generated by Workflow Architect';
	}
}
