/**
 * iOS Swift SDK Template Generator
 * Generates production-ready Swift client code
 */

import type { SDKGenerationOptions, GeneratedSDKFile, MobileConfig } from '../types';

/**
 * Generate Swift SDK
 */
export function generateSwiftSDK(
	config: MobileConfig,
	options: SDKGenerationOptions,
): GeneratedSDKFile[] {
	const files: GeneratedSDKFile[] = [];

	// Main SDK file
	files.push(generateMainSDKFile(config, options));

	// Configuration
	files.push(generateConfigFile(config, options));

	// Models
	files.push(generateModelsFile(config, options));

	// Extensions
	files.push(generateExtensionsFile(options));

	// Package.swift
	files.push(generatePackageFile(options));

	// README
	files.push(generateReadmeFile(config, options));

	if (options.includeExamples) {
		files.push(generateExampleFile(config, options));
	}

	if (options.includeTests) {
		files.push(generateTestFile(options));
	}

	return files;
}

/**
 * Generate main SDK file
 */
function generateMainSDKFile(config: MobileConfig, options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `//
//  ${className}SDK.swift
//  ${options.packageName}
//
//  Generated by Workflow Architect
//  Version: ${options.apiVersion}
//

import Foundation
import Combine

/// Main SDK class for ${className}
@available(iOS ${options.deploymentTarget ?? '14.0'}, *)
public final class ${className}SDK {

    // MARK: - Properties

    /// SDK configuration
    public let configuration: ${className}Configuration

    /// Network client
    private let networkClient: NetworkClient

    /// Authentication manager
    private let authManager: AuthenticationManager

    /// Storage manager
    private let storageManager: StorageManager

    /// Offline manager
    private let offlineManager: OfflineManager

    /// Sync manager
    private let syncManager: SyncManager

    /// Cancellables
    private var cancellables = Set<AnyCancellable>()

    // MARK: - Initialization

    /// Initialize SDK with configuration
    /// - Parameter configuration: SDK configuration
    public init(configuration: ${className}Configuration) {
        self.configuration = configuration
        self.networkClient = NetworkClient(baseURL: configuration.baseURL)
        self.authManager = AuthenticationManager(
            clientId: configuration.clientId,
            redirectUri: configuration.redirectUri
        )
        self.storageManager = StorageManager(encryptionEnabled: configuration.encryptStorage)
        self.offlineManager = OfflineManager(
            maxQueueSize: configuration.maxQueueSize,
            retryAttempts: configuration.retryAttempts
        )
        self.syncManager = SyncManager(
            networkClient: networkClient,
            storageManager: storageManager,
            syncInterval: configuration.syncInterval
        )

        setupObservers()
    }

    // MARK: - Setup

    private func setupObservers() {
        // Observe auth state changes
        authManager.authStatePublisher
            .sink { [weak self] state in
                self?.handleAuthStateChange(state)
            }
            .store(in: &cancellables)

        // Observe network state changes
        NetworkMonitor.shared.isConnectedPublisher
            .sink { [weak self] isConnected in
                self?.handleNetworkStateChange(isConnected)
            }
            .store(in: &cancellables)
    }

    private func handleAuthStateChange(_ state: AuthState) {
        if state == .authenticated {
            syncManager.startSync()
        } else {
            syncManager.stopSync()
        }
    }

    private func handleNetworkStateChange(_ isConnected: Bool) {
        if isConnected {
            offlineManager.processQueue()
        }
    }

    // MARK: - Authentication

    /// Authenticate user
    /// - Returns: Publisher that emits authentication result
    public func authenticate() -> AnyPublisher<AuthResult, Error> {
        authManager.authenticate()
    }

    /// Logout user
    /// - Returns: Publisher that completes when logout is successful
    public func logout() -> AnyPublisher<Void, Never> {
        authManager.logout()
    }

    /// Check if user is authenticated
    public var isAuthenticated: Bool {
        authManager.isAuthenticated
    }

    // MARK: - API Methods

    /// Execute workflow
    /// - Parameters:
    ///   - workflowId: Workflow ID
    ///   - input: Input data
    /// - Returns: Publisher that emits execution result
    public func executeWorkflow(
        _ workflowId: String,
        input: [String: Any]
    ) -> AnyPublisher<ExecutionResult, Error> {
        guard isAuthenticated else {
            return Fail(error: SDKError.notAuthenticated)
                .eraseToAnyPublisher()
        }

        let request = ExecuteWorkflowRequest(
            workflowId: workflowId,
            input: input
        )

        if NetworkMonitor.shared.isConnected {
            return networkClient.send(request)
        } else {
            // Queue for offline processing
            offlineManager.enqueue(request)
            return Just(ExecutionResult.queued(workflowId))
                .setFailureType(to: Error.self)
                .eraseToAnyPublisher()
        }
    }

    /// Get workflow list
    /// - Returns: Publisher that emits workflow list
    public func getWorkflows() -> AnyPublisher<[Workflow], Error> {
        guard isAuthenticated else {
            return Fail(error: SDKError.notAuthenticated)
                .eraseToAnyPublisher()
        }

        return networkClient.send(GetWorkflowsRequest())
    }

    // MARK: - Sync

    /// Start background sync
    public func startSync() {
        syncManager.startSync()
    }

    /// Stop background sync
    public func stopSync() {
        syncManager.stopSync()
    }

    /// Manual sync
    /// - Returns: Publisher that completes when sync is done
    public func sync() -> AnyPublisher<SyncResult, Error> {
        syncManager.sync()
    }

    // MARK: - Cleanup

    deinit {
        cancellables.removeAll()
    }
}

// MARK: - SDK Error

public enum SDKError: LocalizedError {
    case notAuthenticated
    case networkError(Error)
    case invalidResponse
    case decodingError(Error)
    case offline

    public var errorDescription: String? {
        switch self {
        case .notAuthenticated:
            return "User is not authenticated"
        case .networkError(let error):
            return "Network error: \\(error.localizedDescription)"
        case .invalidResponse:
            return "Invalid response from server"
        case .decodingError(let error):
            return "Failed to decode response: \\(error.localizedDescription)"
        case .offline:
            return "Device is offline"
        }
    }
}

// MARK: - Helper Types

public enum AuthState {
    case authenticated
    case unauthenticated
}

public struct AuthResult: Codable {
    public let accessToken: String
    public let refreshToken: String?
    public let expiresIn: Int
}

public struct ExecutionResult: Codable {
    public let id: String
    public let status: String
    public let output: [String: Any]?

    static func queued(_ workflowId: String) -> ExecutionResult {
        ExecutionResult(
            id: UUID().uuidString,
            status: "queued",
            output: ["workflowId": workflowId]
        )
    }

    enum CodingKeys: String, CodingKey {
        case id, status, output
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(String.self, forKey: .id)
        status = try container.decode(String.self, forKey: .status)
        output = try? container.decode([String: Any].self, forKey: .output)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }

    fileprivate init(id: String, status: String, output: [String: Any]?) {
        self.id = id
        self.status = status
        self.output = output
    }
}

public struct Workflow: Codable, Identifiable {
    public let id: String
    public let name: String
    public let description: String?
    public let active: Bool
    public let createdAt: Date
    public let updatedAt: Date
}

public struct SyncResult: Codable {
    public let syncedItems: Int
    public let conflicts: Int
    public let timestamp: Date
}
`;

	return {
		path: `Sources/${className}SDK/${className}SDK.swift`,
		content,
		language: 'swift',
		type: 'source',
	};
}

/**
 * Generate configuration file
 */
function generateConfigFile(config: MobileConfig, options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `//
//  ${className}Configuration.swift
//  ${options.packageName}
//

import Foundation

/// SDK Configuration
public struct ${className}Configuration {

    /// Base URL for API
    public let baseURL: URL

    /// OAuth2 client ID
    public let clientId: String

    /// OAuth2 redirect URI
    public let redirectUri: URL

    /// OAuth2 scopes
    public let scopes: [String]

    /// Enable offline mode
    public let offlineEnabled: Bool

    /// Max offline queue size
    public let maxQueueSize: Int

    /// Retry attempts for failed requests
    public let retryAttempts: Int

    /// Enable sync
    public let syncEnabled: Bool

    /// Sync interval in seconds
    public let syncInterval: TimeInterval

    /// Enable storage encryption
    public let encryptStorage: Bool

    /// Enable certificate pinning
    public let certificatePinning: Bool

    /// Enable biometric authentication
    public let biometricAuth: Bool

    /// Enable analytics
    public let analyticsEnabled: Bool

    // MARK: - Initialization

    public init(
        baseURL: URL,
        clientId: String,
        redirectUri: URL,
        scopes: [String] = [],
        offlineEnabled: Bool = true,
        maxQueueSize: Int = 1000,
        retryAttempts: Int = 3,
        syncEnabled: Bool = true,
        syncInterval: TimeInterval = 300,
        encryptStorage: Bool = true,
        certificatePinning: Bool = true,
        biometricAuth: Bool = true,
        analyticsEnabled: Bool = true
    ) {
        self.baseURL = baseURL
        self.clientId = clientId
        self.redirectUri = redirectUri
        self.scopes = scopes
        self.offlineEnabled = offlineEnabled
        self.maxQueueSize = maxQueueSize
        self.retryAttempts = retryAttempts
        self.syncEnabled = syncEnabled
        self.syncInterval = syncInterval
        self.encryptStorage = encryptStorage
        self.certificatePinning = certificatePinning
        self.biometricAuth = biometricAuth
        self.analyticsEnabled = analyticsEnabled
    }

    /// Default configuration
    public static var `default`: ${className}Configuration {
        ${className}Configuration(
            baseURL: URL(string: "${config.baseUrl}")!,
            clientId: "${config.auth.clientId}",
            redirectUri: URL(string: "${config.auth.redirectUri}")!,
            scopes: ${JSON.stringify(config.auth.scopes ?? [])}
        )
    }
}
`;

	return {
		path: `Sources/${className}SDK/${className}Configuration.swift`,
		content,
		language: 'swift',
		type: 'source',
	};
}

/**
 * Generate models file
 */
function generateModelsFile(config: MobileConfig, options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `//
//  Models.swift
//  ${options.packageName}
//

import Foundation

// MARK: - Request Protocols

protocol APIRequest {
    associatedtype Response: Decodable

    var path: String { get }
    var method: HTTPMethod { get }
    var headers: [String: String] { get }
    var body: Data? { get }
}

enum HTTPMethod: String {
    case get = "GET"
    case post = "POST"
    case put = "PUT"
    case patch = "PATCH"
    case delete = "DELETE"
}

// MARK: - Workflow Requests

struct GetWorkflowsRequest: APIRequest {
    typealias Response = [Workflow]

    let path = "/api/v1/workflows"
    let method = HTTPMethod.get
    let headers: [String: String] = [:]
    let body: Data? = nil
}

struct ExecuteWorkflowRequest: APIRequest {
    typealias Response = ExecutionResult

    let workflowId: String
    let input: [String: Any]

    var path: String {
        "/api/v1/workflows/\\(workflowId)/execute"
    }

    let method = HTTPMethod.post
    let headers: [String: String] = ["Content-Type": "application/json"]

    var body: Data? {
        try? JSONSerialization.data(withJSONObject: input)
    }
}

// MARK: - Device Info

public struct DeviceInfo: Codable {
    public let platform: String
    public let osVersion: String
    public let appVersion: String
    public let deviceId: String
    public let deviceModel: String
    public let locale: String
    public let timezone: String

    public static var current: DeviceInfo {
        DeviceInfo(
            platform: "ios",
            osVersion: UIDevice.current.systemVersion,
            appVersion: Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0.0",
            deviceId: UIDevice.current.identifierForVendor?.uuidString ?? UUID().uuidString,
            deviceModel: UIDevice.current.model,
            locale: Locale.current.identifier,
            timezone: TimeZone.current.identifier
        )
    }
}

// MARK: - Offline Action

struct OfflineAction: Codable {
    let id: String
    let type: ActionType
    let resource: String
    let data: [String: Any]
    let timestamp: Date
    var retryCount: Int
    var status: ActionStatus

    enum ActionType: String, Codable {
        case create = "CREATE"
        case update = "UPDATE"
        case delete = "DELETE"
        case execute = "EXECUTE"
    }

    enum ActionStatus: String, Codable {
        case pending = "PENDING"
        case processing = "PROCESSING"
        case failed = "FAILED"
        case completed = "COMPLETED"
    }
}

// MARK: - Push Notification

public struct PushNotification: Codable {
    public let id: String
    public let title: String
    public let body: String
    public let data: [String: Any]?
    public let badge: Int?
    public let sound: String?
    public let deepLink: String?
    public let timestamp: Date
}
`;

	return {
		path: `Sources/${className}SDK/Models.swift`,
		content,
		language: 'swift',
		type: 'source',
	};
}

/**
 * Generate extensions file
 */
function generateExtensionsFile(options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `//
//  Extensions.swift
//  ${options.packageName}
//

import Foundation

// MARK: - Dictionary Extensions

extension Dictionary where Key == String, Value == Any {
    func jsonData() throws -> Data {
        try JSONSerialization.data(withJSONObject: self)
    }
}

// MARK: - Decodable Extensions

extension Decodable {
    static func decode(from data: Data) throws -> Self {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(Self.self, from: data)
    }
}

// MARK: - Encodable Extensions

extension Encodable {
    func encode() throws -> Data {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        return try encoder.encode(self)
    }
}

// MARK: - URLRequest Extensions

extension URLRequest {
    mutating func setAuthToken(_ token: String) {
        setValue("Bearer \\(token)", forHTTPHeaderField: "Authorization")
    }
}
`;

	return {
		path: `Sources/${className}SDK/Extensions.swift`,
		content,
		language: 'swift',
		type: 'source',
	};
}

/**
 * Generate Package.swift
 */
function generatePackageFile(options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "${options.packageName}",
    platforms: [
        .iOS(.v${options.deploymentTarget?.replace('.', '_') ?? 'v14'})
    ],
    products: [
        .library(
            name: "${className}SDK",
            targets: ["${className}SDK"]
        ),
    ],
    targets: [
        .target(
            name: "${className}SDK",
            dependencies: []
        ),
        .testTarget(
            name: "${className}SDKTests",
            dependencies: ["${className}SDK"]
        ),
    ]
)
`;

	return {
		path: 'Package.swift',
		content,
		language: 'swift',
		type: 'config',
	};
}

/**
 * Generate README
 */
function generateReadmeFile(config: MobileConfig, options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `# ${className} iOS SDK

Production-ready Swift SDK for ${className}.

## Installation

### Swift Package Manager

Add to your \`Package.swift\`:

\`\`\`swift
dependencies: [
    .package(url: "https://github.com/yourorg/${options.packageName}.git", from: "${options.apiVersion}")
]
\`\`\`

### CocoaPods

Add to your \`Podfile\`:

\`\`\`ruby
pod '${className}SDK', '~> ${options.apiVersion}'
\`\`\`

## Quick Start

\`\`\`swift
import ${className}SDK

// Configure SDK
let config = ${className}Configuration(
    baseURL: URL(string: "${config.baseUrl}")!,
    clientId: "your-client-id",
    redirectUri: URL(string: "${config.auth.redirectUri}")!
)

// Initialize
let sdk = ${className}SDK(configuration: config)

// Authenticate
sdk.authenticate()
    .sink(
        receiveCompletion: { completion in
            // Handle completion
        },
        receiveValue: { result in
            print("Authenticated: \\(result.accessToken)")
        }
    )
    .store(in: &cancellables)

// Execute workflow
sdk.executeWorkflow("workflow-id", input: ["key": "value"])
    .sink(
        receiveCompletion: { completion in
            // Handle completion
        },
        receiveValue: { result in
            print("Execution result: \\(result)")
        }
    )
    .store(in: &cancellables)
\`\`\`

## Features

- ✅ OAuth2 authentication with biometric support
- ✅ Offline-first architecture
- ✅ Automatic sync
- ✅ Secure storage (Keychain)
- ✅ Certificate pinning
- ✅ Combine framework integration
- ✅ SwiftUI compatibility

## Requirements

- iOS ${options.deploymentTarget ?? '14.0'}+
- Swift 5.9+
- Xcode 15.0+

## License

See LICENSE file for details.
`;

	return {
		path: 'README.md',
		content,
		language: 'swift',
		type: 'config',
	};
}

/**
 * Generate example file
 */
function generateExampleFile(config: MobileConfig, options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `//
//  Example.swift
//  ${options.packageName}
//

import SwiftUI
import Combine
import ${className}SDK

@main
struct ExampleApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    @StateObject private var viewModel = ExampleViewModel()

    var body: some View {
        NavigationView {
            List {
                Section("Authentication") {
                    if viewModel.isAuthenticated {
                        Text("Authenticated")
                            .foregroundColor(.green)
                        Button("Logout") {
                            viewModel.logout()
                        }
                    } else {
                        Button("Login") {
                            viewModel.login()
                        }
                    }
                }

                Section("Workflows") {
                    ForEach(viewModel.workflows) { workflow in
                        VStack(alignment: .leading) {
                            Text(workflow.name)
                                .font(.headline)
                            if let description = workflow.description {
                                Text(description)
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                }
            }
            .navigationTitle("${className} SDK")
        }
        .onAppear {
            viewModel.setup()
        }
    }
}

class ExampleViewModel: ObservableObject {
    @Published var isAuthenticated = false
    @Published var workflows: [Workflow] = []

    private var sdk: ${className}SDK!
    private var cancellables = Set<AnyCancellable>()

    func setup() {
        let config = ${className}Configuration.default
        sdk = ${className}SDK(configuration: config)
    }

    func login() {
        sdk.authenticate()
            .receive(on: DispatchQueue.main)
            .sink(
                receiveCompletion: { _ in },
                receiveValue: { [weak self] _ in
                    self?.isAuthenticated = true
                    self?.loadWorkflows()
                }
            )
            .store(in: &cancellables)
    }

    func logout() {
        sdk.logout()
            .receive(on: DispatchQueue.main)
            .sink { [weak self] in
                self?.isAuthenticated = false
                self?.workflows = []
            }
            .store(in: &cancellables)
    }

    func loadWorkflows() {
        sdk.getWorkflows()
            .receive(on: DispatchQueue.main)
            .sink(
                receiveCompletion: { _ in },
                receiveValue: { [weak self] workflows in
                    self?.workflows = workflows
                }
            )
            .store(in: &cancellables)
    }
}
`;

	return {
		path: `Examples/ExampleApp.swift`,
		content,
		language: 'swift',
		type: 'example',
	};
}

/**
 * Generate test file
 */
function generateTestFile(options: SDKGenerationOptions): GeneratedSDKFile {
	const className = toPascalCase(options.packageName);

	const content = `//
//  ${className}SDKTests.swift
//  ${options.packageName}
//

import XCTest
import Combine
@testable import ${className}SDK

final class ${className}SDKTests: XCTestCase {
    var sdk: ${className}SDK!
    var cancellables: Set<AnyCancellable>!

    override func setUp() {
        super.setUp()

        let config = ${className}Configuration(
            baseURL: URL(string: "https://api.example.com")!,
            clientId: "test-client",
            redirectUri: URL(string: "test://callback")!
        )

        sdk = ${className}SDK(configuration: config)
        cancellables = Set<AnyCancellable>()
    }

    override func tearDown() {
        sdk = nil
        cancellables = nil
        super.tearDown()
    }

    func testInitialization() {
        XCTAssertNotNil(sdk)
        XCTAssertFalse(sdk.isAuthenticated)
    }

    func testConfiguration() {
        let config = sdk.configuration
        XCTAssertEqual(config.baseURL.absoluteString, "https://api.example.com")
        XCTAssertEqual(config.clientId, "test-client")
    }
}
`;

	return {
		path: `Tests/${className}SDKTests/${className}SDKTests.swift`,
		content,
		language: 'swift',
		type: 'test',
	};
}

/**
 * Convert string to PascalCase
 */
function toPascalCase(str: string): string {
	return str
		.split(/[-_]/)
		.map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
		.join('');
}
